### ISSUE TITLE
Messages.getMessagesById results in 400

### ISSUE THREAD

**Issue by baryonyx5** [shenning00/pyCiscoSparkAPI#1]
I'm getting a bad request response from Spark when using the getMessagesByID method of the Messages class. 

It appears to be because the API does not like the payload format (messages?id=XXX) and wants the ID in the URI.  

Changing line 419 to:
response = self.restReq.get(self.MESSAGES_URL,id=messageId)

got it working for me.

BTW, thanks for making this available.

**Comment by shenning00** [comment]
Thanks so much for the catch. I made the change and I also changed the method name to be "getMessageById" instead of "getMessagesById" - since it will only return one message.

Also, FYI, I split the **init**.py into different class files.

**Comment by shenning00** [comment]
Let me know if you have any other problems. I need to find time to add test cases soon.

**Comment by baryonyx5** [comment]
That fixed it.

At a quick glance I see some typos in the class methods ("pesonEMail" on line 66 of messages.py for instance).

If you’d like, I can do a pull request and submit back any issues I can identify and correct.

Kris Seraphine
Principal Engineer
Phone: +1608-298-1603
Email: kris.seraphine@cdw.commailto:kris.seraphine@cdw.com

On Jan 23, 2016, at 5:52PM, Scott Henning <notifications@github.com<mailto:notifications@github.com>> wrote:

Let me know if you have any other problems. I need to find time to add test cases soon.

**Comment by shenning00** [comment]
Sure. Pull away.

What do you think about the wrapper objects - like Message, Person, etc.? I'm debating whether they are needed and if the API should return a dictionary as the response.

**Comment by baryonyx5** [comment]
I prefer the wrapper objects myself. Your implementation is very similar to how I tend to tackle similar things.

Full disclosure, I don’t have a app-dev background. I’m self-taught (using python in support of my day job) and consider myself at the low end of intermediate skill set  so my opinion is not necessarily worth much.

Kris Seraphine
Principal Engineer
Phone: +1608-298-1603
Email: kris.seraphine@cdw.commailto:kris.seraphine@cdw.com

On Jan 24, 2016, at 12:22PM, Scott Henning <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure. Pull away.

What do you think about the wrapper objects - like Message, Person, etc.? I'm debating whether they are needed and if the API should return a dictionary as the response.
